### ISSUE TITLE
All Demo crashes the firefox nightly browser

### ISSUE THREAD

**Issue by engineer1109** [austinEng/webgpu-samples#104]
The firefox nightly can run wgpu-rs demo.
However, run webgpu-samples will make the firefox crashes...

**Comment by kainino0x** [comment]
Some of the samples work for me but I was able to reproduce a browser crash on mac with the computeBoids demo. This is a Firefox bug though, not a samples bug. @kvark FYI

**Comment by kainino0x** [comment]
Per https://github.com/gpuweb/gpuweb/wiki/Implementation-Status
you can search to see if this has been reported here:
https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=Graphics%3A%20WebGPU&list_id=15685629
and if not, file an issue against that component.

Here's my crash report:
https://crash-stats.mozilla.org/report/index/f4d2e5a7-cb59-46bf-a881-81cb40210423

**Comment by kvark** [comment]
That looks like an issue I fixed recently, but the patch may have been rolled back. In any case, this will work soon.
