### ISSUE TITLE
Atomics support in WGSL

### ISSUE THREAD

**Issue by jiby-gh** [austinEng/webgpu-samples#114]
Hi Austin,

I was curious if it's possible to do atomic operations (eg: atomicAdd) with WGSL, I see these functions in the spec. However, I have been unable to make sure of them in WGSL (works with SPIR-V). Is it that maybe chrome implementation of WGSL does not contain atomics part of spec yet ?

**Comment by kainino0x** [comment]
Correct, Chrome doesn't implement atomics yet, sorry. See: https://crbug.com/tint/742

**Comment by jiby-gh** [comment]
@kainino0x thanks for the bug reference
