### ISSUE TITLE
Take advantage of `var` type omission in WGSL

### ISSUE THREAD

**Issue by Kangz** [austinEng/webgpu-samples#118]
This would make the shaders nicer to read!

**Comment by alyian** [comment]
![IMG_٢٠٢١٠٧٠٩_٠٢٤٥٢١](https://user-images.githubusercontent.com/86137533/125208730-006fc580-e29d-11eb-861c-f56b48dfb468.jpg)

**Comment by alyian** [comment]
![IMG_٢٠٢١٠٧٠٨_١٤٢٦٢٢](https://user-images.githubusercontent.com/86137533/125208752-15e4ef80-e29d-11eb-9ccc-9ee726124d82.jpg)

**Comment by alyian** [comment]
![IMG_٢٠٢١٠٦٠٦_٠٠٥٢٢٨](https://user-images.githubusercontent.com/86137533/125208758-26956580-e29d-11eb-8d5e-f1d467577841.png)

**Comment by alyian** [comment]
![IMG_٢٠٢١٠٦١٦_١١١٤٢٧](https://user-images.githubusercontent.com/86137533/125208800-5a708b00-e29d-11eb-9a48-55c89d077ed6.png)
