### ISSUE TITLE
How to render multi-views?

### ISSUE THREAD

**Issue by laobel** [austinEng/webgpu-samples#119]
Hi, your code helps me a lot. I have a question for you.
How to render multi-views?
I try the following code, but only render the last command!
class Renderer {
    sceneView;

    constructor(sceneView) {
        this.sceneView = sceneView;
    }

    frame() {

        let gpuCommands = [];

        for (let i = 0, len = this.sceneView.viewList.length; i < len; i++) {
            let viewport = this.sceneView.viewList[i];

            viewport.preRender.raiseEvent();

            //gpuCommands.splice(0,0,this.renderViewport(viewport));
            gpuCommands.push(this.renderViewport(viewport));

            viewport.postRender.raiseEvent();
        }

        this.sceneView.device.queue.submit(gpuCommands);
    }

    renderViewport(viewport) {
        // CAMERA BUFFER
        const cameraViewProjectionMatrix = viewport.camera.getCameraViewProjMatrix();
        this.sceneView.device.queue.writeBuffer(
            viewport.cameraUniformBuffer,
            0,
            cameraViewProjectionMatrix.buffer,
            cameraViewProjectionMatrix.byteOffset,
            cameraViewProjectionMatrix.byteLength
        );

        viewport.renderPassDescriptor.colorAttachments[0].view = this.sceneView.swapChain.getCurrentTexture().createView();

        const commandEncoder = this.sceneView.device.createCommandEncoder();
        const passEncoder = commandEncoder.beginRenderPass(viewport.renderPassDescriptor);

        passEncoder.setViewport(viewport.viewRect.x, viewport.viewRect.y, viewport.viewRect.width, viewport.viewRect.height, 0, 1);
        passEncoder.setScissorRect(viewport.viewRect.x, viewport.viewRect.y, viewport.viewRect.width, viewport.viewRect.height);

        for (let object of viewport.scene.Primitives) {
            object.draw(passEncoder, this.sceneView.device, viewport.camera)
        }

        passEncoder.endPass();

        return commandEncoder.finish();
    }
}

**Comment by kainino0x** [comment]
It looks like you are using two separate render passes. Most likely, both render passes clear the render target at the beginning (using `loadValue`). You'll probably want to render both views inside the same render pass, instead.
