### ISSUE TITLE
Deferred rendering inaccurate UV coordinate

### ISSUE THREAD

**Issue by ottoville** [austinEng/webgpu-samples#130]
When I was writing a program inspired by deferred rendering sample, I noticed that current UV mapping algorithm have minimum resolution of 2x2 pixels.

Here is how to see prove that issue:
When adding following lines at the end of "fragmentDeferredRendering.wgsl" before return statement:

```
    let fragCoordI=vec2<i32>(round(coord.xy));
    if(fragCoordI.x > 500) {
      result=vec3<f32>(1.0,0.0,0.0);  //red
    }
    if(fragCoordI.x > 501) {
      result=vec3<f32>(0.0,1.0,0.0);  //green
    }
    if(fragCoordI.x > 502) {
      result=vec3<f32>(0.0,0.0,1.0); //blue
    }
    if(fragCoordI.x > 503) {
      result=vec3<f32>(1.0,1.0,0.0); //yellow
    }
    if(fragCoordI.x > 504) {
      result=vec3<f32>(0.0,1.0,1.0); //cyan
    }
    if(fragCoordI.x > 505) {
      result=vec3<f32>(1.0,0.0,1.0); //pink
    }
```

Expected result is 1px thin red, green, blue, yellow and cyan line to be drawn and right side of image to be pink.
Here is a screenshot from actual results: 
![image](https://user-images.githubusercontent.com/2173773/127921818-4f363e37-3121-462c-ab04-5af1004fe8d0.png)

When zooming to very close, it is visible that only green and yellow line is visible, both being 2px wide:
![image](https://user-images.githubusercontent.com/2173773/127921921-76834dc0-fc10-48f3-8349-61c5617f0bc3.png)

The 2x2 pixel resolution is also clearly visible when looking aliasing of edges of the squares in the sample page
![image](https://user-images.githubusercontent.com/2173773/127922742-982742d0-f7e8-45f6-8206-b616b2990fb1.png)

**Comment by kainino0x** [comment]
@shrekshao

**Comment by shrekshao** [comment]
Seems to be `round` is behaving incorrectly in chrome canary win
Here's 4x4 texture attachment with `image-rendering: pixelated; for canvas css style`
in `fragmentDeferredRendering.wgsl` I added
```
var cc:vec2<i32> = vec2<i32>(floor(coord.xy));
//var cc:vec2<i32> = vec2<i32>(round(coord.xy));
var colors = array<vec3<f32>, 8>(
      vec3<f32>(1.0, 0.0, 0.0),
      vec3<f32>(1.0, 0.5, 0.0),
      vec3<f32>(1.0, 1.0, 0.0),
      vec3<f32>(0.0, 1.0, 0.0),
      vec3<f32>(0.0, 1.0, 1.0),
      vec3<f32>(0.0, 0.5, 1.0),
      vec3<f32>(0.0, 0.0, 1.0),
      vec3<f32>(0.5, 0.0, 1.0)
);
result = colors[(cc.x + cc.y) % 8];
```

```
var cc:vec2<i32> = vec2<i32>(floor(coord.xy));
```
![image](https://user-images.githubusercontent.com/5031596/127936633-e6f23806-0ac7-4f63-94ef-58fcbc9e6e7b.png)


```
var cc:vec2<i32> = vec2<i32>(round(coord.xy));
```
![image](https://user-images.githubusercontent.com/5031596/127936765-b7ba1654-0a5b-4368-9d34-16beb49792dc.png)


I will try testing on other platform, come up with a minimal test and report to tint (likely a tint bug)

Thanks for the report!

**Comment by shrekshao** [comment]
Filed at https://bugs.chromium.org/p/tint/issues/detail?id=1089
