### ISSUE TITLE
Examples don't work on Firefox. navigator.gpu is undefined

### ISSUE THREAD

**Issue by kirdaybov** [austinEng/webgpu-samples#144]
I tried opening examples (https://austin-eng.com/webgpu-samples/samples/helloTriangle) on Firefox Nightly 94.0a1 (2021-09-24) (64-bit) and I get the following:
```
Hello Triangle
See it on Github!
Shows rendering a basic triangle.
Is WebGPU Enabled?
TypeError: can't access property "requestAdapter", navigator.gpu is undefined
```

I've also tried to set flags `dom.webgpu.enabled=true` and `gfx.webrender.all=true` as suggested in one of the articles on the subject. Then, counterintuitively, I get the following:
```
Hello Triangle
See it on Github!
Shows rendering a basic triangle.
Is WebGPU Enabled?
InvalidStateError: WebGPU is not enabled!
```

**Comment by kainino0x** [comment]
This sounds like either a Firefox issue or a hardware support issue. Do the examples work for you in Chrome/Chromium?

**Comment by kirdaybov** [comment]
@kainino0x Yes, they work in Google Chrome Canary

**Comment by cx20** [comment]
I have confirmed that the sample works on Firefox Nightly 94.0a1 (2021-09-24) (64-bit).
Environment: Windows 10 + NVIDIA GeForce RTX 2060 + Firefox Nightly 94.0a1

**Comment by kirdaybov** [comment]
@cx20 ok, I've just tried again and it started working. Maybe I had to restart the browser. I'm closing the issue
