### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by jespertheend** [austinEng/webgpu-samples#147]
Just a heads up that the certificate for austin-eng.com expired :)

**Comment by austinEng** [comment]
yea I'm looking into it. I don't manage it. It's through Github so idk what's going on :o

**Comment by austinEng** [comment]
I clicked the button to make it try again in the Pages settings several times and now it's working? (for me at least).

**Comment by jespertheend** [comment]
Not sure what but it seems like something is cached on my end. It's working fine in incognito 👍

**Comment by jespertheend** [comment]
Ah restarting my browser fixed it, thanks!
