### ISSUE TITLE
Module not found: Can't resolve 'stanford-dragon/4'

### ISSUE THREAD

**Issue by yangfangfang1204** [austinEng/webgpu-samples#148]
Module not found: Can't resolve 'stanford-dragon/4'
i run the demo in https://github.com/austinEng/webgpu-samples ,first npm install , and npm start ,there is a error Module not found: Can't resolve 'stanford-dragon/4 ?

**Comment by shrekshao** [comment]
I encountered this on my mac, node v16.15.1, npm 8.11.0.
And I get it fixed by `rm -rf node_modules/` and then `npm install`. Will you try this?

**Comment by austinEng** [comment]
Closing as there has bee no feedback. Please reopen if you run into further issues.
