### ISSUE TITLE
Uniform size in shadow-mapping is not aligned to 16 bytes

### ISSUE THREAD

**Issue by kvark** [austinEng/webgpu-samples#149]
I think this is still a problem with WebGPU/WGSL spec, but I want it to be visible here anyway, so that I can point people to this.
The example uses the following code to initialize the uniform buffer:
```js
  const sceneUniformBuffer = device.createBuffer({
    // Two 4x4 viewProj matrices,
    // one for the camera and one for the light.
    // Then a vec3 for the light position.
    size: 2 * 4 * 16 + 3 * 4,
    usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
  });
```

The size of the buffer is not aligned to 16 bytes, which currently triggers a validation error with Firefox, since the shader-reflected size is treated as aligned, and it's bigger than the bound size. Current code in this example matches https://github.com/gpuweb/gpuweb/issues/1558 but contradicts https://github.com/gpuweb/gpuweb/issues/425.

**Comment by austinEng** [comment]
I don't recall when this was fixed, but I checked just now that it is correctly aligned.
