### ISSUE TITLE
Particles example not working

### ISSUE THREAD

**Issue by nicchann** [austinEng/webgpu-samples#154]
The particles example just shows a black screen for me.

I'm on Chrome 96.0.4664.93

```
Tint WGSL reader failure:
Parser: 24:3 error: invalid character found
  _ = &buf_in;
  ^
...
 - While calling CreateShaderModule([ShaderModuleDescriptor]).
[CommandBuffer] is an error.
    at ValidateObject (../../third_party/dawn/src/dawn_native/Device.cpp:473)
    at ValidateSubmit (../../third_party/dawn/src/dawn_native/Queue.cpp:384)
```

**Comment by cx20** [comment]
I think that sample works in Chrome Canary. 
It still doesn't seem to work in Chrome 96 due to a recent specification change.

https://hackmd.io/@webgpu/Hk-AbOWvK#New-deprecations

**Comment by austinEng** [comment]
Maybe in the future we'll try to keep deprecated code working for older versions of Chrome. But for now I'll close this due to the spec change.
