### ISSUE TITLE
Fragment output type confusion of gBufferPass in example `Deferred Rendering`

### ISSUE THREAD

**Issue by onsummer** [austinEng/webgpu-samples#162]
The output struct has been declare in `fragmentWriteGBuffers.wgsl`:

``` wgsl
struct GBufferOutput {
  [[location(0)]] position : vec4<f32>;
  [[location(1)]] normal : vec4<f32>;
  [[location(2)]] albedo : vec4<f32>;
}
```

I notice that the third color attachment target format is `'bgra8unorm'`, it is a 32-bits texture format

```typescript
const writeGBuffersPipeline = device.createRenderPipeline({
  vertex: {
    module: device.createShaderModule({
      code: vertexWriteGBuffers,
    }),
    entryPoint: 'main',
    buffers: vertexBuffers,
  },
  fragment: {
    module: device.createShaderModule({
      code: fragmentWriteGBuffers,
    }),
    entryPoint: 'main',
    targets: [
      // position
      { format: 'rgba32float' },
      // normal
      { format: 'rgba32float' },
      // albedo
      { format: 'bgra8unorm' },
    ],
  },
  depthStencil: {
    depthWriteEnabled: true,
    depthCompare: 'less',
    format: 'depth24plus',
  },
  primitive,
});
```

But `GBufferOutput.albedo` is `vec4<f32>`, a 32-bytes member, are `'bgra8unorm'` and `'vec4<f32>'` compatible?

Thank you for your examples that I learn a lot.

**Comment by austinEng** [comment]
bgra8unorm means that the components are B, G, R, A, each of which is an 8-byte *unsigned normalized integer*.

This means that 0 maps to 0.0f, and 255 maps to 1.0f.

So when the `GBufferOutput.albedo` floating-point values are actually written out to the texture, they're stored as integers in the range 0-255.

**Comment by onsummer** [comment]
I use an example to illustrate my understanding.

If let the `output.albedo` be an special value, such as:

```wgsl
// in fragment stage entry function

var output: GBufferOutput;
output.albedo = vec4<f32>(0.51, 0.89, 0.25, 1.0);

return output;
```

finaly, written to the texture, that texel value is mapping from `(0.51, 0.89, 0.25, 1.0)` to `(130, 227, 64, 255)` (each float32 component multiple 255 and then take floor operation to be integer)?

That is to say, no matter what target format is, the output from fragment shader will automatically mapping to it?

**Comment by austinEng** [comment]
Yes, though the specific operation "each float32 component multiple 255 and then take floor operation to be integer" may be hardware dependent and not exactly that computation.

**Comment by onsummer** [comment]
> Yes, though the specific operation "each float32 component multiple 255 and then take floor operation to be integer" may be hardware dependent and not exactly that computation.

Thank you very much!😘
