### ISSUE TITLE
i didn't watch anythings... it is appearing black screen on position of 3D Grapics(maybe made by WebGPU)

### ISSUE THREAD

**Issue by dotori1995-enu** [austinEng/webgpu-samples#170]
Environment: 
OS: Window10
graphics card: GeForce RTX 2070
WebBrowser: Chrome

it is the Error Message
" Uncaught TypeError: Failed to execute 'beginRenderPass' on 'GPUCommandEncoder': Failed to read the 'colorAttachments' property from 'GPURenderPassDescriptor': Failed to read the 'loadValue' property from 'GPURenderPassColorAttachment': Failed to read the 'loadValue' property from 'GPURenderPassColorAttachment': Required member is undefined. "

and 
Environment: 
OS: Window10
graphics card: GeForce RTX 2070
WebBrowser: Chrome canary

it is the Error Message
"/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()"
"commons.12f668dc692cf6ef6acf.js:1 TypeError: Cannot read properties of null (reading 'requestDevice')
    at 19.9fd01fdfbfda2698d105.js:1:1039
    at l (commons.12f668dc692cf6ef6acf.js:1:175043)
    at Generator._invoke (commons.12f668dc692cf6ef6acf.js:1:174831)
    at Generator.next (commons.12f668dc692cf6ef6acf.js:1:175468)
    at r (commons.12f668dc692cf6ef6acf.js:1:65853)
    at u (commons.12f668dc692cf6ef6acf.js:1:66056)"

**Comment by ndtrek07** [comment]
The first error above also observed in HelloTriangle example, running from https://austin-eng.com/

Uncaught TypeError: Failed to execute 'beginRenderPass' on 'GPUCommandEncoder': Failed to read the 'colorAttachments' property from 'GPURenderPassDescriptor': Failed to read the 'loadValue' property from 'GPURenderPassColorAttachment': Failed to read the 'loadValue' property from 'GPURenderPassColorAttachment': Required member is undefined.
    at p (/webgpu-samples/_nex…7f4f85a02d.js:1:672)

Ubuntu 18.04
Chrome: Version 99.0.4844.82 (Official Build) (64-bit)
NVIDIA GeForce GTX 970

**Comment by ndtrek07** [comment]
To clarify the above comment: The error is displayed, and the demo does not work. It appears to affect **every** example on https://austin-eng.com/webgpu-samples

**Comment by adrian154** [comment]
Cannot reproduce the error on Chrome Canary 102, but can reproduce in Chrome 99.

**Comment by austinEng** [comment]
Sorry for the breaking change in Chrome. M102 is stable now, so this issue is obsolete.
