### ISSUE TITLE
Black screen and error msg helloTriangle

### ISSUE THREAD

**Issue by DeepDeeh** [austinEng/webgpu-samples#175]
Browser: 
Name 	Firefox
Version 	101.0a1
Build-ID 	20220405094056
about:config
dom.webgpu.enabled= true
gfx.webgpu.force-enabled=true
gfx.webrender.software=false

OS:
Ubuntu 20.04.4 LTS
Linux 5.8.18-050818-generic 

GPU:
AMD® Radeon rx 5700 xt
Vulkan Instance Version: 1.3.204
Extended renderer info (GLX_MESA_query_renderer):
Vendor: AMD (0x1002)
Device: AMD Radeon RX 5700 XT (NAVI10, DRM 3.42.0, 5.8.18-050818-generic, LLVM 12.0.0) (0x731f)
Version: 21.2.6

Issue:
Black screen in all demos.
![helloTriangle](https://user-images.githubusercontent.com/40594404/161849294-5cbd88d1-79f8-4df7-98b2-759dae8be8cf.png)

**Comment by austinEng** [comment]
Unfortunately, this broke for Chrome Stable, but should be working in Chrome Canary. I'm not sure if there's a way we can make it work in both or if a breaking change has occurred.

Does Canary work for you?

**Comment by austinEng** [comment]
Going to close this issue since it seems to be a problem with a particular WebGPU implementation, and not the samples.
