### ISSUE TITLE
WebGPU "GPU connection lost" regression in Chrome canary version 103.5044.0

### ISSUE THREAD

**Issue by lisanlow** [austinEng/webgpu-samples#177]
@austinEng I was developing on webgpu application on Chrome canary today and I suddenly started getting "GPU connection lost" and rendering fails on my webgpu application.

I observed the same failure on your samples: https://austin-eng.com/webgpu-samples/samples/helloTriangle
This regression started with Chrome canary version 103.5044.0, it was working fine with version 103.5043.1

Did you observe the same failure?
Any idea how to overcome it?

![GPUConnectionLost](https://user-images.githubusercontent.com/11375089/166949318-9b1d0c5d-1206-46f7-90c9-5ed8a58a2b44.PNG)

**Comment by cx20** [comment]
I saw a similar issue with Chrome Canary `103.0.9999.0`. I also want to know the solution.

**Comment by cx20** [comment]
I tried the sample again on Chrome Canary today and it displayed fine.
When I checked the version of Chrome Canary with [WebGL Report](https://webglreport.com/), it was `103.0.9999.0`, but it seems that it was actually `103.0.5046.0`.

**Comment by lisanlow** [comment]
Yes, I verified that its fixed in Chrome canary version 103.0.5046.0

**Comment by XYCaptain** [comment]
Do not works on Chrome Canary 104.0.5063.0 .

**Comment by austinEng** [comment]
this is a known issue being tracked in crbug.com/1322823 (sorry it's not public) but I'll update here if it gets fixed as well.

**Comment by XYCaptain** [comment]
> this is a known issue being tracked in crbug.com/1322823 (sorry it's not public) but I'll update here if it gets fixed as well.

Thanks very much. Edge Canary Dev works well for testing.

**Comment by austinEng** [comment]
A fix was landed in https://chromium-review.googlesource.com/c/chromium/src/+/3648575

You can track when it is available in Canary here: https://chromiumdash.appspot.com/commit/2ab3924df9894cfba339ce1765eab3d3da22994f
