### ISSUE TITLE
Why do these work in Chrome?

### ISSUE THREAD

**Issue by neriymus** [austinEng/webgpu-samples#198]
Just wondering why these examples are working in Chrome (not Canary). I thought webgpu is hidden behind a flag in Chrome Canary? Thanks

**Comment by puxiao** [comment]
**Chrome 105**

https://github.com/austinEng/webgpu-samples/blob/main/src/pages/_app.tsx
```
<meta
          httpEquiv="origin-trial"
          content="........"
/>
```

But maybe you can't run it in chrome at the moment, because the origin-trial has expired, I applied for a new one.
https://github.com/austinEng/webgpu-samples/pull/203

**Comment by puxiao** [comment]
The origin trial is expected to [pause for 2 weeks](https://groups.google.com/a/chromium.org/g/blink-dev/c/gBMsYQ1Aurw/m/xl1znc7fAAAJ) starting in Chrome 106 (Sep 27, 2022).

**Comment by austinEng** [comment]
The pause should end on 10/18. We were delayed a bit. For now you can run Chrome with `--enable-unsafe-webgpu`
