### ISSUE TITLE
ImageBlur sample is broken

### ISSUE THREAD

**Issue by tlecoz** [austinEng/webgpu-samples#207]
Hello, 
I've been studying your code everydays for 3 weeks and today I observed that ImageBlur sample doesn't work anymore. 
I almost never looked at this sample so I don't know exactly when it stopped to work but it's recent , 2 weeks max. 

![image](https://user-images.githubusercontent.com/272817/198976617-854b5df8-f107-49d8-abc4-23300258e0b5.png)

By the way, do you have an approximative idea of the release date of webgpu inside stable version of chrome ? Do you think it's more likely to be in 2023 or in 2024 ?

**Comment by ben-clayton** [comment]
Thank you for filing this issue.

This is due to the texture queries changing signedness (spec change).
I'll create a PR to fix this shortly.

> By the way, do you have an approximative idea of the release date of webgpu inside stable version of chrome ? Do you think it's more likely to be in 2023 or in 2024 ?

Specifications are stabilising, and implementation is catching up fairly rapidly. We're aiming for early 2023.

**Comment by ben-clayton** [comment]
Hopefully fixed with https://github.com/austinEng/webgpu-samples/pull/208

**Comment by tlecoz** [comment]
Wow thank you for your reactivity ! 

> We're aiming for early 2023.

Great news !

**Comment by austinEng** [comment]
Checked that this is fixed now! thanks for filing the issue :)
