### ISSUE TITLE
Particle demo doesn't work on Pixel 6

### ISSUE THREAD

**Issue by mfoltzgoogle** [austinEng/webgpu-samples#225]
I tried the WebGPU particle demo on my Pixel 6 and the particles didn't animate at all. The entire browser was very janky and the display started flickering.

This was on Chrome Canary 112.0.5574.0 on Android TP1A.221105.002 with the unsafe-gpu flag enabled

**Comment by austinEng** [comment]
This is a Chrome issue - I filed https://crbug.com/1414835 about it.
