### ISSUE TITLE
how to gernerate mimap texture?

### ISSUE THREAD

**Issue by redcamel** [austinEng/webgpu-samples#25]
how to gernerate mimap texture?

**Comment by shrekshao** [comment]
I asked this question on Oct 11 2019. There's no such function implemented in WebGPU at this moment. (There's plan to write a properly working one) "So for now you could either write a helper function, or use WebGL to generate the mipmaps for you"

Please feel free to add any up-to-date info if there is any.

**Comment by redcamel** [comment]
@shrekshao thank you for your answer.
