### ISSUE TITLE
HelloTriangle sample is not displayed in Chrome Canary for Mac

### ISSUE THREAD

**Issue by cx20** [austinEng/webgpu-samples#27]
I tried to display the following sample in Chrome Canary for Mac.
https://austineng.github.io/webgpu-samples/#helloTriangle
https://austineng.github.io/webgpu-samples/#helloTriangleMSAA
However, there is no error on the console and nothing is displayed on the screen.
Strangely, samples other than the above are displayed without problems.

The environment I tried is as follows.
MacBook Air + Intel UHD Graphics 617 + MacOS X + Chrome Canary 81.0.3998.0 : NG
MacBook Air + Intel UHD Graphics 617 + Win10(BootCamp) + Chrome Canary 81.0.3998.0 : OK

**Comment by austinEng** [comment]
Hi @cx20, the root cause of this problem is an issue in the Metal driver on Intel Macs. There's compiling a particular array syntax in Metal Shading Language. Please see this related issue for more information https://github.com/KhronosGroup/SPIRV-Cross/issues/1210.

**Comment by cx20** [comment]
@austinEng Thank you for the information. I confirmed that HelloTriangle sample is displayed by changing the MacOS X version from `10.14.6` to `10.15.2`.
