### ISSUE TITLE
Broken row pitch computation or implementation

### ISSUE THREAD

**Issue by frguthmann** [austinEng/webgpu-samples#29]
I was trying to understand what the row pitch computation was doing so I built the textured cube sample locally and tried with a different image. I simply scaled down the provided image from 512 x 512 px to 500 x 500 px.  Here is the result:

![Untitled](https://user-images.githubusercontent.com/4346296/71419416-a7ffb580-266f-11ea-8b1c-3d8989d77280.png)

I'm not sure what is going on as the row pitch parameter is not described in the WebGPU
Editor’s Draft. Is this a normal behavior in the current state of implementation?

**Comment by kainino0x** [comment]
It is similar to row pitch concepts in other APIs. In WebGPU it is the
number of bytes between the beginning of each row of the texture, in the
buffer's memory space. Row pitch must be a multiple of 256 bytes. So you'll
have to insert extra padding between rows if they're not a multiple of 256
bytes in length.

There is, or soon will be (I don't remember the exact status), a limited
implementation of copyImageBitmapToTexture in Chrome which makes it much
easier to get image data into GPUTextures. You can take a look at the test
for example: https://github.com/gpuweb/cts/pull/95

I am pretty sure our implementation is correct, but I won't guarantee it. :)

**Comment by frguthmann** [comment]
Hi, thanks for the quick answer! It makes sense and this is what the code in the textured cube example is doing. However, the only thing I changed to break this example is the source image :/. If I can, I'll try on another computer. (This one has an old driver and card)

Good to know, it could indeed be made easier :).

Haha no problem, it's pretty easy to test anyway.

**Comment by frguthmann** [comment]
Here is a minimal example to reproduce the bug I'm seeing. I have tested it on a second computer with the same result. At the beginning of texturedCube.js, you can choose between the 512x512 px image or the 500x500 px one. The only difference in code execution as far as I can tell is in the row pitch computation in helpers.js, line 33.

https://glitch.com/edit/#!/crimson-monitor?path=texturedCube.js:1:0

PS: While I'm having fun investigating WebGPU during this holiday season, I'm not expecting you to answer right away. This is absolutely not urgent matter :).

**Comment by frguthmann** [comment]
Added pull request https://github.com/austinEng/webgpu-samples/pull/30 to fix the problem.
