### ISSUE TITLE
avoiding memory growth.

### ISSUE THREAD

**Issue by trusktr** [austinEng/webgpu-samples#32]
https://github.com/austinEng/webgpu-samples/blob/6d74973c0ef2be83386cb6092e94a8eca0cb2214/src/examples/rotatingCube.ts#L182

Just curious: that line makes a new object every frame it seems. Is there a better way so it doesn't grow memory each frame? Can that function be called once, outside the frame? Or does it need to be called every time?

If it needs to be called every time, maybe making the object arg outside of frame would help a little.

**Comment by austinEng** [comment]
This `{}` is completely unnecessary (the argument is optional), and could just be
```js
const commandEncoder = device.createCommandEncoder();
```

If you'd like, you could open a PR to remove it.

That being said, do you have profiles of this causing a huge bloat in memory growth or expensive GC's? I'd be very interested in seeing them if so, as it would help us motivate optimizations.

Creating an object here, per frame, _shouldn't_ be an issue. It should be short-lived and cleaned up in the cheap GC of the young object generation.
