### ISSUE TITLE
All the examples not displayed in Mac Canary Chrome

### ISSUE THREAD

**Issue by xiaoiver** [austinEng/webgpu-samples#33]
Here's my environment: 
* Mac Pro 10.15.3
* Chrome Canary  83.0.4092.0
* Intel Iris Pro 1536 MB

When I open every example in browser, the console log the following:
```
Push constants aren't supported.
Object is an error.
```

I searched the issues and found this one https://github.com/austinEng/webgpu-samples/issues/27.
So the root cause is in the Metal driver on Intel Macs right?

**Comment by xiaoiver** [comment]
It works after upgrading `glslang`:
* before `https://unpkg.com/@webgpu/glslang@0.0.7/web/glslang.js`
* after `https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js`

**Comment by cx20** [comment]
The same applies to Chrome Canary in Windows environment.

**Comment by kainino0x** [comment]
@austinEng can you repoint these samples at https://unpkg.com/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js?
