### ISSUE TITLE
Getting getMappedRange is not a function in Firefox Nightly 80

### ISSUE THREAD

**Issue by talentlessguy** [austinEng/webgpu-samples#49]
Hello, even though it's mentioned on the first page that it works on Chrome Canary, first two demos also work fine on FF Nightly - without any errors

but the rest of the demos breaks, because I get this error:

```js
Uncaught (in promise) TypeError: d.getMappedRange is not a function
```

I don't think it's worth spending time on resolving an issue, but just in case anyone faces an issue too, where only first two demos work - most probably FF webgpu hasn't implemented `GPUBuffer.getMappedRange` yet

**Comment by rvadhavk** [comment]
I just tried on Firefox Nightly 89.0a1 and getMappedRange works now.
