### ISSUE TITLE
Async/Await odd image loading behavior on Chrome Canary 87.0.4249.0

### ISSUE THREAD

**Issue by sortofsleepy** [austinEng/webgpu-samples#51]
First off, thanks so much for putting these samples up! 🎉 🎉 It's been a great resource to learn from, really appreciate the time you put into this.

This is more a question really and not anything wrong with the samples themselves; I've basically been building myself a toy framework based on these samples. One thing I noticed today while following the textured cube example is that image loading seems to be weird in the version of Canary I have; it's possible this is more a question for the Chromium team but figured I'd start here since this is where I first encountered this behavior. 

Anyways, basically, on my computer, it seems like image loading in general ends up blocking WebGPU from rendering things to the screen for some reason. The code I have now 

* appears to load fine
* there are no errors,
* there are no warnings

 just nothing renders to the screen. The weird thing is, when I resize the window however, things render as expected. Even something simple like this 

```javascript

let loadImage = async ()=>{
  let img = new Image();
  img.src ="test.jpg"
  await img.decode();
}

async function run(){

   // if this line is un-commented, nothing renders until I resize the window.
   let img = await loadImage();

  // more WebGPU code to render something 
}
``` 

causes this behavior to manifest.

I was hoping that you might have some kind of idea as to what is happening? If not that's cool, but figured it couldn't hurt to ask. 

Thanks!

**Comment by kainino0x** [comment]
This repo is actually maintained by members of the Chromium team, so either way you're in the right place. :)

Are you using asynchronous rendering code inside of requestAnimationFrame? The callback to requestAnimationFrame is not expected to be async, so only the code up to the first `await` will actually occur before the canvas contents are captured and displayed to the screen.

**Comment by sortofsleepy** [comment]
> This repo is actually maintained by members of the Chromium team, so either way you're in the right place. :)

Oh! That's very convenient haha. Well then a big thank you to you and the entire team then! 🎉 
 
> Are you using asynchronous rendering code inside of requestAnimationFrame? The callback to requestAnimationFrame is not expected to be async, so only the code up to the first `await` will actually occur before the canvas contents are captured and displayed to the screen.

No, nothing async is happening inside of requestAnimation frame, the basic structure right now pretty much looks like this (in mostly pseudocode/comments)

```javascript
let loadImage = async ()=>{
    // texture loading code
}
export default async function(_instance){


   let texture = await loadTexture();
    
   // setup matrices for the "camera"

   let vertexBuffer = setupVertexBuffer();
   let bindGroup = setupBindgroup()
   setupShader();
   setupPipeline();
   // more WebGPU setup

   let animate = () => {
     requestAnimationFrame(animate);
    // webgpu rendering code 
  }
  animate();


}

```

I could have swore I mentioned this but I didn't apparently - if it happens to help, I've run very similar code in the past with no issues; I ran into this recently while trying to update things to follow the updated spec for how to map data to buffers.

**Comment by kainino0x** [comment]
Hm, then I don't have any more ideas right now about what could be wrong. Would you be able to make a small standalone test case that narrows down the issue?

BTW, if you're not using it already, we do now implement `copyImageBitmapToTexture` and you might be able to use that instead. (But even if that works around the issue, we still need to make sure the browser is behaving correctly in both cases, so the reduced test case would still be helpful.)

**Comment by sortofsleepy** [comment]
Sure thing, might not be able to get to it till the weekend but I can put together a small test case.

**Comment by sortofsleepy** [comment]
This may be a case of user error as it turns out, barebones sample and it works haha. Closing for now. Will re-open if something more obvious comes up. 

Thank you!

**Comment by kainino0x** [comment]
No worries, good luck figuring it out!

**Comment by austinEng** [comment]
Hey @sortofsleepy! I found perhaps the same bug and filed it https://bugs.chromium.org/p/chromium/issues/detail?id=1124952 . There's at least one Chrome bug where reconfiguring the swapchain doesn't dirty the canvas until the window is resized. It's likely you were running into the same thing.
