### ISSUE TITLE
save and reload doesn't work as expected

### ISSUE THREAD

**Issue by dneto0** [austinEng/webgpu-samples#55]
I'd like to modify the example and try again, e.g. to change the triangle colour.

When I save, Chrome makes an HTML page and a directory of supporting files.
When I load the HTML file, any time I click on an example in the pane on the left, it loads it from your website rather than from the local files. So I don't get the effect of may source code change.

**Comment by kainino0x** [comment]
Making browser-save-page-as work properly is probably pretty tricky. You could check out the master branch (requires a build step), or you could check out the gh-pages branch and edit the js directly in there.

**Comment by austinEng** [comment]
Save and edit would be awfully convenient though. Right now the page is programmatically put together at runtime. At some point I was going to try to make this a static build time step which would make saving the page probably/hopefully significantly easier.

**Comment by austinEng** [comment]
Anyway, not sure if you were actually trying to save/edit the entire page, or if you were misled by the text on the page that says you can save to edit the shaders. But I was inspired to make the live-editing functionality a bit better. I updated it to be a bit more clear, added an "Update Shaders" button, and have it capture Cmd+S or Ctrl+S depending on platform.

When you save while the editor has focus, or you click the update button, it'll live update the shaders in the page.
