### ISSUE TITLE
Not working on Firefox Nightly 82.0a1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by ikamthania** [austinEng/webgpu-samples#57]
I enabled both flags `dom.webgpu.enabled` and `gfx.webrender.all`. Gpu is AMD R9-380, vulkan version 1.2.148 All samples results in this error
```
Uncaught (in promise) TypeError: GPUDevice.createRenderPipeline: Missing required 'layout' member of GPUPipelineDescriptorBase.
    createRenderPipeline index.js:27
    createRenderPipeline index.js:27
    i computeBoids.ts:23
    r computeBoids-0af943.js:1
    promise callback*c computeBoids-0af943.js:1
    r computeBoids-0af943.js:1
    promise callback*c computeBoids-0af943.js:1
    r computeBoids-0af943.js:1
```
Works fine on Chrome canary on Macos.

**Comment by kainino0x** [comment]
This is because the implementations are incomplete, and Firefox is missing the particular feature that allows `layout` to be omitted and computed implicitly.

It's unfortunate that this breaks all the samples. Maybe it would be worth avoiding this feature in the samples for the moment? Or should we just wait for Firefox to implement this? cc @kvark

**Comment by kvark** [comment]
We have a limited support for implicit layout in `wgpu`, but there is still a large gap between this and what Gecko currently uses. We are working on it. I think it's fine to have the example broken for now.

**Comment by ikamthania** [comment]
Thanks for the info. Should I close the issue then ?

**Comment by kvark** [comment]
It's basically impossible to consider any incompatibility to be a bug on either side until the API is somewhat stable, i.e. at least some sort of an MVP that we all agree on. While it's in motion, there will be breakage.
Therefore, we can close this for now
