### ISSUE TITLE
An error occorred when using wgsl

### ISSUE THREAD

**Issue by HypnosNova** [austinEng/webgpu-samples#59]
Today I updated chrome canary.

Before I updated the browser, demo works well, but after I updated the chrome canary, all the demos using wgsl failed.

In console, it shows: 
![image](https://user-images.githubusercontent.com/7953802/95313627-eb57a780-08c2-11eb-8ef1-88d5d91b85fc.png)

**Comment by kainino0x** [comment]
Sorry, we are in the middle of changing things here. We'll update the samples ASAP.

**Comment by austinEng** [comment]
Sorry, so we had some WGSL changes that broke a lot of functionality in Chrome so this isn't going to be fixed immediately.
You can follow along at https://bugs.chromium.org/p/tint/issues/detail?id=267 if you're interested.

Right now only the triangle and basic cube examples work with WGSL.

**Comment by austinEng** [comment]
Nevermind, fixed the texture stuff in #61 and also added WGSL shaders for the remaining samples that didn't have it.

Now the only ones that don't work with WGSL are compute_boids and animometer since they use std lib functions. Will be fixed in https://dawn-review.googlesource.com/c/tint/+/29841 .
