### ISSUE TITLE
Source code for dist/utils.js wasm 

### ISSUE THREAD

**Issue by vorg** [austinEng/webgpu-samples#6]
Any chance that source of dist/utils.js wasm will be provided?

**Comment by fernandojsg** [comment]
@vorg it is basically this https://github.com/austinEng/webgpu-samples/blob/master/utils.js with the webgpu/shaderc wasm package inside (https://github.com/kainino0x/-webgpu-shaderc)

**Comment by vorg** [comment]
Ok. But then https://github.com/kainino0x/-webgpu-shaderc is also just binary blob with no source? e.g. where are shaderc.js shaderc.wasm from?

**Comment by austinEng** [comment]
@kainino0x has a branch to build `shaderc` as a wasm binary here https://github.com/kainino0x/shaderc/tree/wasm

**Comment by kainino0x** [comment]
Sorry the build process is not very well documented. I will improve it when I have an opportunity.

**Comment by frguthmann** [comment]
> Sorry the build process is not very well documented. I will improve it when I have an opportunity.

Please do! A simple run "npm run build" and then run a local server in the root folder would have saved me an hour of figuring out what the hell was going on...

**Comment by kainino0x** [comment]
It's still not extremely well documented but please use the newer package @webgpu/glslang https://www.npmjs.com/package/@webgpu/glslang instead of the old shaderc package (now deprecated)

**Comment by kainino0x** [comment]
The build script for the glslang package is in its GitHub repo.
