### ISSUE TITLE
not working on Chrome canary

### ISSUE THREAD

**Issue by jack1232** [austinEng/webgpu-samples#70]
Hi,

I got the following error when running the examples on Chrome canary (64-bit) version 89.0.4380.0:

Uncaught (in promise) TypeError: m.device.createBufferMapped is not a function.

It just showed a black screen.

Please advice.

**Comment by kainino0x** [comment]
Are you on the latest revision of this repository's `main` branch? I can't find any leftover instances of the (removed) createBufferMapped function in the code.

**Comment by kainino0x** [comment]
You may need to rebuild with `npm run build`

**Comment by jack1232** [comment]
Thanks,

Rebuilding works.
