### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by jack1232** [austinEng/webgpu-samples#75]
The samples worked few days ago. However, after updating Chrome Canary to Version 89.0.4387.3 (Official Build) canary (64-bit), suddenly, none of the samples work with the following error (same for all samples):

TypeError: Cannot read property 'requestDevice' of null
    at rotatingCube-6f3dd6430b02cabc591c.js:1
    at l (1be8be7c52e2349f8660686032d2042ae0b6bb9e.08d4626ed8f6bcf6d877.js:1)
    at Generator._invoke (1be8be7c52e2349f8660686032d2042ae0b6bb9e.08d4626ed8f6bcf6d877.js:1)
    at Generator.next (1be8be7c52e2349f8660686032d2042ae0b6bb9e.08d4626ed8f6bcf6d877.js:1)
    at r (5e050aff538434ccde2cc97438110cf81079bf6a.910cf116a21df707471b.js:1)
    at s (5e050aff538434ccde2cc97438110cf81079bf6a.910cf116a21df707471b.js:1)

it seems that it can get webgpu context but not the device.

**Comment by austinEng** [comment]
Hm, what OS are you on? I just tested with 89.0.4387.3 (Official Build) canary (x86_64) on Mac and it works ok.

**Comment by jack1232** [comment]
windows 10.

**Comment by austinEng** [comment]
If you have `--enable-unsafe-webgpu` enabled and `await navigator.gpu.requestAdapter()` is resolving to null (can just check that in a dev tools console),

then could you please file a bug on crbug.com and attach the contents of about://gpu

**Comment by jack1232** [comment]
Yes, the '--enable-unsafe-webgpu' flag is enabled. and find 'await navigator.gpu.requestAdapter()' is indeed resolving to null in the console.

OK, I will file a bug report there.

**Comment by austinEng** [comment]
Chromium bug.

**Comment by liudonghua123** [comment]
An origin trial token is needed on websites that wish to display WebGPU content to users. A token can be created [here](https://developer.chrome.com/origintrials/).

> https://discourse.threejs.org/t/would-love-to-view-the-webgpu-examples-requires-origin-trial-token/44123

**Comment by kainino0x** [comment]
Note WebGPU is shipping ungated in Chrome 113 releasing May 2 (and the origin trial has been removed since it doesn't do anything anymore).
https://chromiumdash.appspot.com/schedule

**Comment by liudonghua123** [comment]
Can't wait to use the new Chrome 113. ✌️

**Comment by kainino0x** [comment]
You can use it already in the Beta channel (or Chrome 114 in the Dev/Canary channels). 🙂

**Comment by liudonghua123** [comment]
I would like to use the stable channel, or I will get two version of chrome. Wait for May 2 to update my exist chrome.
