### ISSUE TITLE
Canvas size should incorporate devicePixelRatio

### ISSUE THREAD

**Issue by kainino0x** [austinEng/webgpu-samples#79]
On my display I usually use a browser scale factor >100%, which means the difference between the MSAA and non-MSAA triangles is hard to see (edges are blurred either way). If we set the canvas size according to devicePixelRatio then we'll get sharper rendering and clearer results.

Doing this properly will require the canvas to change size at runtime though, and Chrome at least might still have issues with that, I'm not sure.

**Comment by austinEng** [comment]
Last time I checked, reconfiguring the swap chain due to window resize worked.

**Comment by munrocket** [comment]
This was fixed in #124
