### ISSUE TITLE
Handedness discusion

### ISSUE THREAD

**Issue by shrekshao** [austinEng/webgpu-samples#87]
The NDC coordinate of WebGPU is left-handed; NDC coordinate of WebGL is ~~right handed~~ left handed (I'm confused again).

Right now our sample uses everything in right-handed: model coordinate (cube.ts), world coordinate (several transformation), perspective matrix (from gl-matrix). So the result turns out to be correct.

Wondering what a good common behavior for future WebGPU dev community should be (likely somewhat affected by this webgpu-samples) . Although this seems to be something that engine level app needs to consider (https://github.com/KhronosGroup/UnityGLTF/issues/257, unity engine uses left-handed, glTF model uses right-handed, and unity takes care of conversion at import time)

If most model assets inherit from WebGL age would be targeted at right-handed coordinate, it makes sense to just keep everything right-handed?

**Comment by shrekshao** [comment]
It seems the only thing matter is +x would be right and +y would be up. Other than that it's just a matter of the choice of the engine. Like the reversed z showed, z could be 0,1 or 1,0. Both would work fine as long as other pipeline matches (depth compare method, projection matrix value)

**Comment by kainino0x** [comment]
@toji for gl-matrix

**Comment by shrekshao** [comment]
Based on https://github.com/austinEng/webgpu-samples/pull/85#issuecomment-811984877 and some of my own thinking afterwards, this issue seems to be only a matter of choice at the render app level.
