### ISSUE TITLE
Support WHLSL in addition to SPIR-V for testing with safari tech previews..

### ISSUE THREAD

**Issue by oscarbg** [austinEng/webgpu-samples#9]
for example apple has hooked up compute support:
https://trac.webkit.org/changeset/246427/webkit
https://trac.webkit.org/browser/webkit/trunk/LayoutTests/webgpu/whlsl-compute.html?rev=246427
and sample in that patch shows it supports feeding WHLSL directly..

**Comment by Kangz** [comment]
We don't have WHLSL expertise and learning it would require reading Safari's source code to know the differences with regular HLSL. Would accept PRs though.

**Comment by litherum** [comment]
> reading Safari's source code

Don't you mean the language specification? https://github.com/gpuweb/WHLSL/blob/master/Spec/source/index.rst

**Comment by Kangz** [comment]
At the time of this comment my understanding was that the Safari implementation didn't match the spec (yet?). Would still accept PRs.

**Comment by austinEng** [comment]
Closing this as WHLSL is not the shading language for WebGPU. The group has decided on [WGSL](https://gpuweb.github.io/gpuweb/wgsl.html). Please see #44 instead about updating shaders to use WGSL.
