### ISSUE TITLE
All demos fail on Firefox Nightly 89.0a1 with missing field error

### ISSUE THREAD

**Issue by rvadhavk** [austinEng/webgpu-samples#91]
`Uncaught TypeError: GPUCommandEncoder.beginRenderPass: Missing required 'view' member of GPURenderPassColorAttachmentDescriptor.`

According to the spec, the view parameter is required now: https://gpuweb.github.io/gpuweb/#color-attachments, so just passing that in the `beginRenderPass` should fix the issue.

**Comment by austinEng** [comment]
Ah, this used to be be called `attachment`. We'll have to update that in the Typescript types, update it in Chrome and update it in these samples too.

**Comment by kvark** [comment]
Can be closed now
