### ISSUE TITLE
Incompatible internal usages in ImageBlur example

### ISSUE THREAD

**Issue by cjj19970505** [austinEng/webgpu-samples#92]
In ImageBlur example, compute shader layout is 
```spir-v
layout(set = 1, binding = 1) uniform texture2D inputTex;
layout(set = 1, binding = 2, rgba8) uniform writeonly image2D outputTex;
layout(set = 1, binding = 3) uniform Uniforms {
  uint uFlip;
};
```
where `inputTex`'s internal usage is [constants](https://gpuweb.github.io/gpuweb/#internal-usage-constant) and `outputTex`'s internal usage is [storage-write](https://gpuweb.github.io/gpuweb/#internal-usage-storage-write), they are not in same [compatible-usage-list](https://gpuweb.github.io/gpuweb/#compatible-usage-list). Binding same textures into these two entries should result in error states for both passEncoder and commandEncoder.  

But in the following code , `texture[0]` and `texture[1]` are bound to `inputTex` and then `outputTex` repeatly in same passEncoder.
```typescript
const computeBindGroup0 = device.createBindGroup({
    layout: blurPipeline.getBindGroupLayout(1),
    entries: [
      {
        binding: 1,
        resource: cubeTexture.createView(),
      },
      {
        binding: 2,
        resource: textures[0].createView(),
      },
      {
        binding: 3,
        resource: {
          buffer: buffer0,
        },
      },
    ],
  });

  const computeBindGroup1 = device.createBindGroup({
    layout: blurPipeline.getBindGroupLayout(1),
    entries: [
      {
        binding: 1,
        resource: textures[0].createView(),
      },
      {
        binding: 2,
        resource: textures[1].createView(),
      },
      {
        binding: 3,
        resource: {
          buffer: buffer1,
        },
      },
    ],
  });

  const computeBindGroup2 = device.createBindGroup({
    layout: blurPipeline.getBindGroupLayout(1),
    entries: [
      {
        binding: 1,
        resource: textures[1].createView(),
      },
      {
        binding: 2,
        resource: textures[0].createView(),
      },
      {
        binding: 3,
        resource: {
          buffer: buffer0,
        },
      },
    ],
  });
```
```typescript
const computePass = commandEncoder.beginComputePass();
    computePass.setPipeline(blurPipeline);
    computePass.setBindGroup(0, computeConstants);

    computePass.setBindGroup(1, computeBindGroup0);
    computePass.dispatch(
      Math.ceil(srcWidth / blockDim),
      Math.ceil(srcHeight / batch[1])
    );
    computePass.dispatch(2, Math.ceil(srcHeight / batch[1]));

    computePass.setBindGroup(1, computeBindGroup1);
    computePass.dispatch(
      Math.ceil(srcHeight / blockDim),
      Math.ceil(srcWidth / batch[1])
    );

    for (let i = 0; i < settings.iterations - 1; ++i) {
      computePass.setBindGroup(1, computeBindGroup2);
      computePass.dispatch(
        Math.ceil(srcWidth / blockDim),
        Math.ceil(srcHeight / batch[1])
      );

      computePass.setBindGroup(1, computeBindGroup1);
      computePass.dispatch(
        Math.ceil(srcHeight / blockDim),
        Math.ceil(srcWidth / batch[1])
      );
    }
```

**Comment by kainino0x** [comment]
Compute passes differ from render passes in this way:

https://gpuweb.github.io/gpuweb/#programming-model-synchronization

> - In a compute pass, each dispatch command (dispatch() or dispatchIndirect()) is one usage scope. A subresource is "used" in the usage scope if it’s accessible by the command. Within a dispatch, every subresource in every currently bound GPUBindGroup is "used" in the usage scope. State-setting compute pass commands, like setBindGroup(index, bindGroup, dynamicOffsets), do not contribute directly to a usage scope; they instead change the state that is checked in dispatch commands.
> - One render pass is one usage scope. A subresource is "used" in the usage scope if it’s referenced by any (state-setting or non-state-setting) command. For example, in setBindGroup(index, bindGroup, dynamicOffsets), every subresource in bindGroup is "used" in the render pass’s usage scope.
